name: Deploy Streamlit App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Poppler
        run: |
          sudo apt-get update
          sudo apt-get install -y poppler-utils

      - name: Deploy to Streamlit Sharing
        uses: actions/checkout@v2
        env:
          STREAMLIT_SHARING_USERNAME: ${{ secrets.STREAMLIT_SHARING_USERNAME }}
          STREAMLIT_SHARING_PASSWORD: ${{ secrets.STREAMLIT_SHARING_PASSWORD }}
        run: |
          pip install streamlit-sharing-deploy
          streamlit-sharing-deploy --app your_app.py
