jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Tesseract OCR and Poppler
        run: |
          sudo apt update
          sudo apt install -y tesseract-ocr libtesseract-dev poppler-utils

      - name: Verify Poppler Installation
        run: |
          pdfinfo -v  # Verify the version of pdfinfo to ensure it's installed
          which pdfinfo  # Check if pdfinfo is available in PATH

      - name: Show PATH and modify if necessary
        run: |
          echo "PATH=$PATH"
          echo "Poppler Path: $(which pdfinfo)"
          PATH=$PATH:$(dirname $(which pdfinfo))
          echo "Modified PATH=$PATH"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests or scripts
        run: python your_script.py
