jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      
      - name: Install OCR and Poppler
        run: |
          sudo apt update
          sudo apt install -y tesseract-ocr
          sudo apt install -y libtesseract-dev
          sudo apt install -y poppler-utils  # This line installs Poppler

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests or scripts
        run: python your_script.py
