jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Poppler
      run: sudo apt-get install -y poppler-utils
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run script
      run: python your_script.py
